# config/routes.yaml

# Import routes from controllers
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Define routes
app_movies:
    path: /movies
    controller: App\Controller\MovieController::index

top5movies:
    path: /api/top5movies
    controller: App\Controller\TopRatedController::getTopRatedMovies

top5series:
    path: /api/top5series
    controller: App\Controller\TopRatedController::getTopRatedTvShows

movies:
    path: /api/movies/{page}
    controller: App\Controller\MovieController::index
    methods: GET
    requirements:
        page: \d+

tv_shows:
    path: /api/tv-shows/{page}
    controller: App\Controller\TvShowController::index
    methods: GET
    requirements:
        page: \d+

register:
    path: /api/register
    controller: App\Controller\UserController::register
    methods: POST

favorites:
    path: /api/favorites
    controller: App\Controller\UserController::addFavorite
    methods: POST

movie_search:
    path: /api/movies
    controller: App\Controller\MovieController::search
    methods: GET

movies_show:
    path: /movies/{id}
    controller: App\Controller\MovieController::show
    requirements:
        id: '\d+'

tv_show:
    path: /tvshow/{id}
    controller: App\Controller\TvShowController::show
    requirements:
        id: '\d+'

app_movie_trailer:
    path: /movies/{id}/trailer
    controller: App\Controller\MovieController::getMovieTrailer
    methods: GET

watch_trailer:
  path: /movies/{id}/watch-trailer
  controller: App\Controller\MovieController::watchTrailer
  methods: GET

tvshow_trailer:
    path: /tvshow/{id}/trailer
    controller: App\Controller\TvShowController::getTvShowTrailer
    methods: GET

watchtvshow_trailer:
  path: /tvshow/{id}/watch-trailer
  controller: App\Controller\TvShowController::watchTrailer
  methods: GET

user_favorite_movie:
  path: /users/{userId}/favorites/movies/{movie_id}
  controller: App\Controller\UserController::addFavoriteMovie
  methods: POST
  requirements:
    id: '\d+'
    movieId: '\d+'

user_favorite_movieAPI:
  path: /users/{userId}/movies/{movieId}/favorites/from-api
  controller: App\Controller\UserController::addFavoriteMovieFromApi
  methods: POST

user_list_favorite_movies:
  path: /users/{id}/favorite-movies
  controller: App\Controller\UserController::getFavorites
  methods: GET

delete_favorite_movie:
    path: /users/{id}/favorite-movies/{movieId}
    controller: App\Controller\UserController::deleteFavorite
    methods: DELETE
    requirements:
        id: '\d+'
        movieId: '\d+'